development: &default
  adapter: postgresql
  database: bzp_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: bzp_test

production: &deploy
  adapter: postgresql
  database: bzp_development
  encoding: utf8
  min_messages: warning
  timeout: 5000

staging: *deploy
